### PR TITLE
Ignore ignored properties in diff from assertRender

### LINKED ISSUE #42: Filter out ignored properties when throwing the assertion error?
**Enhancement**

Shall we consider filtering out those ignored properties when throwing the assertion error? Since we ignore them during `diff`, if we don't ignore them when printing the error out, the console error diff log can be misleading since the error showing on the console is not the actual cause of the error. One good example is `bind`, which [becomes an ignored property](https://github.com/dojo/test-extras/pull/39), and it is a large one too. Currently the error log contains `bind`:
```
AssertionError: Render unexpected

  {
...
A   "bind": {
A     "_allClasses": {
A       "radio-m__checked__1JpbM": false,
A       "radio-m__disabled__2DHjm": false,
A       "radio-m__inputWrapper__EvHGM": false,
A       "radio-m__input__a6UKx": false,
A       "radio-m__invalid__vH9mx": false,
A       "radio-m__readonly__3WqpF": false,
A       "radio-m__required__1ZLJk": false,
A       "radio-m__root__2bqGM": false
A     },
A     "_baseThemeClassesReverseLookup": {
A       "dojo-radio": " _key",
A       "radio-m__checked__1JpbM": "checked",
A       "radio-m__disabled__2DHjm": "disabled",
A       "radio-m__inputWrapper__EvHGM": "inputWrapper",
A       "radio-m__input__a6UKx": "input",
A       "radio-m__invalid__vH9mx": "invalid",
A       "radio-m__readonly__3WqpF": "readonly",
A       "radio-m__required__1ZLJk": "required",
A       "radio-m__root__2bqGM": "root",
A       "radio-m__valid__2hLww": "valid"
A     },
A     "_bindFunctionPropertyMap": {},
A     "_cachedChildrenMap": {},
A     "_children": [
A       length: 0
A     ],
...
```

Package Version: `2.0.0-alpha.3`

### PR DESCRIPTION
**Pull request by maier49**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**
Instead of checking each property during comparison for whether it's ignored, this frontloads that and creates new objects with only those properties that should be compared. That same logic is then used to generate a new "actual" and "expected" for the error message if there are differences.

Resolves #42 

Example of error message from widgets before these changes:
```
× TextInput - simple (0.001s)
AssertionError: Render unexpected

    "aria-controls": undefined,
    "aria-describedby": undefined,
    "aria-invalid": null,
    "aria-readonly": null,
A   "bind": {
A     "_allClasses": {
A       "textinput-m__inputWrapper__qgMQw": false,
A       "textinput-m__input__2KJg7": false,
A       "textinput-m__root__FUuHt": false
A     },
A     "_baseThemeClassesReverseLookup": {
A       "dojo-textinput": " _key",
A       "textinput-m__disabled__302VV": "disabled",
A       "textinput-m__inputWrapper__qgMQw": "inputWrapper",
A       "textinput-m__input__2KJg7": "input",
A       "textinput-m__invalid__CqUAw": "invalid",
A       "textinput-m__readonly__3qX-J": "readonly",
A       "textinput-m__required__55ZjP": "required",
A       "textinput-m__root__FUuHt": "root",
A       "textinput-m__valid__Qu18X": "valid"
A     },
A     "_bindFunctionPropertyMap": {},
A     "_cachedChildrenMap": {},
A     "_children": [
A       length: 0
A     ],
A     "_decoratorCache": {},
A     "_diffPropertyFunctionMap": {},
A     "_dirty": false,
A     "_previousProperties": {
A       "bind": {
A         "_afterCreate": <anonymous>({}),
A         "_bindFunctionPropertyMap": {},
A         "_cachedChildrenMap": {},
A         "_children": [
A           length: 0
A         ],
A         "_decoratorCache": {},
A         "_diffPropertyFunctionMap": {},
A         "_dirty": false,
A         "_id": "test--harness-20",
A         "_previousProperties": {},
A         "_properties": {
A           "bind": [Circular]
A         },
A         "_registries": {
A           "_registries": [
A             0: {
A               "registry": {
A                 "handles": [
A                   length: 0
A                 ],
A                 "listenersMap": {},
A                 "on": <anonymous>({}),
A                 "registry": {}
A               }
A             },
A             length: 1
A           ],
A           "handles": [
A             length: 0
A           ],
A           "listenersMap": {},
A           "on": <anonymous>({})
A         },
A         "_renderDecorators": {},
A         "_renderState": 3,
A         "_widgetConstructor": SpyRender({}),
A         "assertionMessage": undefined,
A         "didRender": true,
A         "expectedRender": undefined,
A         "handles": [
A           0: {
A             "_registries": [
A               0: {
A                 "registry": {
A                   "handles": [
A                     length: 0
A                   ],
A                   "listenersMap": {},
A                   "on": <anonymous>({}),
A                   "registry": {}
A                 }
A               },
A               length: 1
A             ],
A             "handles": [
A               length: 0
A             ],
A             "listenersMap": {},
A             "on": <anonymous>({})
A           },
A           1: {
A             "destroy": destroy({})
A           },
A           2: {
A             "destroy": destroy({})
A           },
A           3: [Circular],
A           length: 4
A         ],
A         "lastRender": {
A           "children": [
A             0: {
A               "children": [
A                 0: {
A                   "children": [
A                     length: 0
A                   ],
A                   "properties": [Circular],
A                   "render": render({}),
A                   "tag": "input",
A                   "type": Symbol(Identifier for a HNode.)
A                 },
A                 length: 1
A               ],
A               "properties": {
A                 "bind": [Circular],
A                 "classes": {
A                   "textinput-m__inputWrapper__qgMQw": true,
A                   "textinput-m__input__2KJg7": false
A                 }
A               },
A               "render": render({}),
A               "tag": "div",
A               "type": Symbol(Identifier for a HNode.)
A             },
A             length: 1
A           ],
A           "properties": {
A             "bind": [Circular],
A             "classes": {
A               "textinput-m__inputWrapper__qgMQw": false,
A               "textinput-m__input__2KJg7": false,
A               "textinput-m__root__FUuHt": true
A             }
A           },
A           "render": render({}),
A           "tag": "div",
A           "type": Symbol(Identifier for a HNode.)
A         },
A         "listenersMap": {},
A         "on": <anonymous>({}),
A         "renderCount": 1
A       }
A     },
A     "_properties": {
A       "bind": {
A         "_afterCreate": <anonymous>({}),
A         "_bindFunctionPropertyMap": {},
A         "_cachedChildrenMap": {},
A         "_children": [
A           length: 0
A         ],
A         "_decoratorCache": {},
A         "_diffPropertyFunctionMap": {},
A         "_dirty": false,
A         "_id": "test--harness-20",
A         "_previousProperties": {},
A         "_properties": {
A           "bind": [Circular]
A         },
A         "_registries": {
A           "_registries": [
A             0: {
A               "registry": {
A                 "handles": [
A                   length: 0
A                 ],
A                 "listenersMap": {},
A                 "on": <anonymous>({}),
A                 "registry": {}
A               }
A             },
A             length: 1
A           ],
A           "handles": [
A             length: 0
A           ],
A           "listenersMap": {},
A           "on": <anonymous>({})
A         },
A         "_renderDecorators": {},
A         "_renderState": 3,
A         "_widgetConstructor": SpyRender({}),
A         "assertionMessage": undefined,
A         "didRender": true,
A         "expectedRender": undefined,
A         "handles": [
A           0: {
A             "_registries": [
A               0: {
A                 "registry": {
A                   "handles": [
A                     length: 0
A                   ],
A                   "listenersMap": {},
A                   "on": <anonymous>({}),
A                   "registry": {}
A                 }
A               },
A               length: 1
A             ],
A             "handles": [
A               length: 0
A             ],
A             "listenersMap": {},
A             "on": <anonymous>({})
A           },
A           1: {
A             "destroy": destroy({})
A           },
A           2: {
A             "destroy": destroy({})
A           },
A           3: [Circular],
A           length: 4
A         ],
A         "lastRender": {
A           "children": [
A             0: {
A               "children": [
A                 0: {
A                   "children": [
A                     length: 0
A                   ],
A                   "properties": [Circular],
A                   "render": render({}),
A                   "tag": "input",
A                   "type": Symbol(Identifier for a HNode.)
A                 },
A                 length: 1
A               ],
A               "properties": {
A                 "bind": [Circular],
A                 "classes": {
A                   "textinput-m__inputWrapper__qgMQw": true,
A                   "textinput-m__input__2KJg7": false
A                 }
A               },
A               "render": render({}),
A               "tag": "div",
A               "type": Symbol(Identifier for a HNode.)
A             },
A             length: 1
A           ],
A           "properties": {
A             "bind": [Circular],
A             "classes": {
A               "textinput-m__inputWrapper__qgMQw": false,
A               "textinput-m__input__2KJg7": false,
A               "textinput-m__root__FUuHt": true
A             }
A           },
A           "render": render({}),
A           "tag": "div",
A           "type": Symbol(Identifier for a HNode.)
A         },
A         "listenersMap": {},
A         "on": <anonymous>({}),
A         "renderCount": 1
A       }
A     },
A     "_recalculateClasses": false,
A     "_registeredBaseThemes": [
A       0: {
A         " _key": "dojo-textinput",
A         "disabled": "textinput-m__disabled__302VV",
A         "input": "textinput-m__input__2KJg7",
A         "inputWrapper": "textinput-m__inputWrapper__qgMQw",
A         "invalid": "textinput-m__invalid__CqUAw",
A         "readonly": "textinput-m__readonly__3qX-J",
A         "required": "textinput-m__required__55ZjP",
A         "root": "textinput-m__root__FUuHt",
A         "valid": "textinput-m__valid__Qu18X"
A       },
A       length: 1
A     ],
A     "_registeredClassesMap": {},
A     "_registries": {
A       "_registries": [
A         0: {
A           "registry": {
A             "handles": [
A               length: 0
A             ],
A             "listenersMap": {},
A             "on": <anonymous>({}),
A             "registry": {}
A           }
A         },
A         length: 1
A       ],
A       "handles": [
A         length: 0
A       ],
A       "listenersMap": {},
A       "on": <anonymous>({})
A     },
A     "_renderDecorators": {},
A     "_renderState": 3,
A     "_theme": {},
A     "handles": [
A       0: {
A         "_registries": [
A           0: {
A             "registry": {
A               "handles": [
A                 length: 0
A               ],
A               "listenersMap": {},
A               "on": <anonymous>({}),
A               "registry": {}
A             }
A           },
A           length: 1
A         ],
A         "handles": [
A           length: 0
A         ],
A         "listenersMap": {},
A         "on": <anonymous>({})
A       },
A       1: {
A         "destroy": destroy({})
A       },
A       2: {
A         "destroy": destroy({})
A       },
A       3: {
A         "destroy": destroy({})
A       },
A       length: 4
A     ],
A     "listenersMap": {},
A     "on": <anonymous>({})
A   },
    "classes": {
      "textinput-m__input__2KJg7": true
    },
    "disabled": undefined,
[...]
    "placeholder": undefined,
    "readOnly": undefined,
    "required": undefined,
    "type": "text",
E   "value": undefined,
E   "whoopsy": "bad"
A   "value": undefined
  }
```
And after:
```
× TextInput - simple (0.007s)
AssertionError: Render unexpected

    "placeholder": undefined,
    "readOnly": undefined,
    "required": undefined,
    "type": "text",
E   "value": undefined,
E   "whoopsy": "bad"
A   "value": undefined
  }

```

### CODE REVIEW

**Comment by agubler** [comment]
@kitsonk are you happy with these changes?

File: src/support/compare.ts [hunk 1]
```diff
@@ -459,6 +447,41 @@ function diffPlainObject(a: any, b: any, options: DiffOptions): (ConstructRecord
...
+	}, {} as any);
+
+	const comparableB = keys(b).reduce((obj, name) => {
+		if (ignore.has(name) || !keep.has(name) && isIgnoredProperty(name)) {
+			return obj;
+		}
+
+		obj[name] = b[name];
+		return obj;
+	}, {} as any);
```
Comment (kitsonk) [inline src/support/compare.ts]: Don't like the cast as `any`, can't we use `as { [key: string]: any; }`?

File: src/support/compare.ts [hunk 2]
```diff
@@ -459,6 +447,41 @@ function diffPlainObject(a: any, b: any, options: DiffOptions): (ConstructRecord
...
+		if (isIgnoredProperty(name) ||
+			hasOwnProperty.call(b, name) && isIgnoredPropertyValue(name, a, b, ignorePropertyValues)) {
+				ignore.add(name);
+				return obj;
+		}
+
+		keep.add(name);
+		obj[name] = a[name];
+		return obj;
+	}, {} as any);
```
Comment (kitsonk) [inline src/support/compare.ts]: Don't like the cast as `any`, can't we use `as { [key: string]: any; }`?

File: src/support/compare.ts [hunk 3]
```diff
@@ -459,6 +447,41 @@ function diffPlainObject(a: any, b: any, options: DiffOptions): (ConstructRecord
 	return patchRecords;
 }
 
+export function getComparableObjects(a: any, b: any, options: DiffOptions) {
```
Comment (kitsonk) [inline src/support/compare.ts]: Would have liked some JSDoc here...

File: src/support/compare.ts [hunk 4]
```diff
@@ -459,6 +447,41 @@ function diffPlainObject(a: any, b: any, options: DiffOptions): (ConstructRecord
...
+	const { ignoreProperties = [], ignorePropertyValues = [] } = options;
+	const ignore = new Set<string>();
+	const keep = new Set<string>();
+
+	function isIgnoredProperty(name: string) {
```
Comment (kitsonk) [inline src/support/compare.ts]: Small nit, but couldn't we create a function that wouldn't have to check `Array.isArray()` on each invocation, since it is not going to change types during the whole of the out function, right?

**Review by kitsonk — COMMENTED** [review]
A couple comments...

**Comment by maier49** [comment]
@kitsonk Updated this to address your feedback

**Review by kitsonk — APPROVED** [review]
Awesome! 💯
